## Clustering movies

We cluster movies from user ratings using hierarchical and k-means clustering.  Note, the clusters are written to files.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Import the ratings

In [3]:
ratingsData = pd.read_csv('ratings.csv')
ratingsData.head()

   user id  item id  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205

### Import the movie data

In [4]:
movieName = pd.read_csv('movies.csv')
numMovies = len(movieName)
movieName.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

### Create a user by movie matrix that we will cluster.

Note, this will take a moment.

In [5]:
userID = np.unique(ratingsData['user id'])
numUsers = len(userID)
userMovieMatrix = np.zeros((numUsers,numMovies))

for i in range(len(ratingsData)): 
    currentUser   = ratingsData['user id'][i] 
    currentMovie  = ratingsData['item id'][i]
    currentRating = ratingsData['rating'][i]
    
    userIndex = np.where(userID == currentUser)[0]
    movieIndex = np.where(movieName['movieId'] == currentMovie)[0] 
    userMovieMatrix[userIndex,movieIndex] = currentRating

### Let’s now apply hierarchical clustering

In [8]:
from sklearn.cluster import AgglomerativeClustering

numberOfClusters = 20

hierarchicalCluster = AgglomerativeClustering(n_clusters=numberOfClusters, affinity='euclidean', linkage='single')  
hierarchicalCluster.fit_predict(userMovieMatrix.T)

array([10,  0,  0, ...,  0,  0,  0])

In [9]:
import sys
original_stdout = sys.stdout

with open('movieClusterHierarchical.txt', 'w') as f: 
   sys.stdout = f
   # Output the clusters
   for i in range(numberOfClusters):
       index = np.where(hierarchicalCluster.labels_ == i)[0]
       print('\n\nCluster %d' % i)
       for j in range(len(index)):
           print(movieName['title'][index[j]])
   sys.stdout = original_stdout

### Let’s now apply k-means clustering

In [7]:
numberOfClusters = 20
from sklearn.cluster import KMeans
kmeansCluster = KMeans(n_clusters=numberOfClusters)
kmeansCluster.fit(userMovieMatrix.T)
y_kmeans = kmeansCluster.predict(userMovieMatrix.T)

In [8]:
import sys
original_stdout = sys.stdout

with open('movieClusterKmeans.txt', 'w') as f: 
   sys.stdout = f
   # Output the clusters
   for i in range(numberOfClusters):
       index = np.where(kmeansCluster.labels_ == i)[0]
       print('Cluster %d' % i)
       for j in range(len(index)):
           print(movieName['title'][index[j]])
   sys.stdout = original_stdout

### Let's see what cluster a movie of your choice resides.

In [9]:
yourMovie = 'Karate Kid, The (1984)'

indexOfYourMovieInDataFrame = np.where(movieName['title']==yourMovie)[0]

clusterOfMovie = kmeansCluster.labels_[indexOfYourMovieInDataFrame]
index = np.where(kmeansCluster.labels_ == clusterOfMovie)[0]
print('\nk-means cluster')
print('===============')
for j in range(len(index)):
     print(movieName['title'][index[j]])

# clusterOfMovie = hierarchicalCluster.labels_[indexOfYourMovieInDataFrame]
# index = np.where(hierarchicalCluster.labels_ == clusterOfMovie)[0]
# print('\n\nhierarchical cluster')
# print('===============')
# for j in range(len(index)):
#      print(movieName['title'][index[j]])

k-means cluster
===============
Grumpier Old Men (1995)
Father of the Bride Part II (1995)
Copycat (1995)
Powder (1995)
Pocahontas (1995)
Indian in the Cupboard, The (1995)
From Dusk Till Dawn (1996)
Muppet Treasure Island (1996)
Rumble in the Bronx (Hont faan kui) (1995)
Bad Boys (1995)
Casper (1995)
Congo (1995)
Desperado (1995)
First Knight (1995)
Johnny Mnemonic (1995)
Judge Dredd (1995)
Mallrats (1995)
Nine Months (1995)
Species (1995)
Strange Days (1995)
Billy Madison (1995)
Tommy Boy (1995)
Naked Gun 33 1/3: The Final Insult (1994)
Reality Bites (1994)
River Wild, The (1994)
Carlito's Way (1993)
City Slickers II: The Legend of Curly's Gold (1994)
Coneheads (1993)
Dazed and Confused (1993)
Free Willy (1993)
Hot Shots! Part Deux (1993)
Kalifornia (1993)
Last Action Hero (1993)
Robin Hood: Men in Tights (1993)
Rudy (1993)
So I Married an Axe Murderer (1993)
Three Musketeers, The (1993)
Brady Bunch Movie, The (1995)
Heavy Metal (1981)
Aristocats, The (1970)
Primal Fear (1996)
Courage Under Fire (1996)
Dragonheart (1996)
Mystery Science Theater 3000: The Movie (1996)
Space Jam (1996)
Hunchback of Notre Dame, The (1996)
Cable Guy, The (1996)
Kingpin (1996)
Eraser (1996)
Nutty Professor, The (1996)
Time to Kill, A (1996)
Ransom (1996)
Tin Cup (1996)
Cool Runnings (1993)
Cinderella (1950)
Sword in the Stone, The (1963)
Robin Hood: Prince of Thieves (1991)
Bedknobs and Broomsticks (1971)
Alice in Wonderland (1951)
Lawnmower Man, The (1992)
That Thing You Do! (1996)
Swingers (1996)
Sleepers (1996)
Dirty Dancing (1987)
Basic Instinct (1992)
Doors, The (1991)
Escape from New York (1981)
Good, the Bad and the Ugly, The (Buono, il brutto, il cattivo, Il) (1966)
Army of Darkness (1993)
Better Off Dead... (1985)
Evil Dead II (Dead by Dawn) (1987)
Akira (1988)
Highlander (1986)
Alien³ (a.k.a. Alien 3) (1992)
Dracula (Bram Stoker's Dracula) (1992)
Cape Fear (1991)
Carrie (1976)
Nightmare on Elm Street, A (1984)
Omen, The (1976)
Star Trek: First Contact (1996)
Die Hard 2 (1990)
Star Trek: The Motion Picture (1979)
Star Trek VI: The Undiscovered Country (1991)
Star Trek V: The Final Frontier (1989)
Star Trek III: The Search for Spock (1984)
Star Trek IV: The Voyage Home (1986)
Batman Returns (1992)
Young Guns (1988)
Young Guns II (1990)
Jaws 2 (1978)
Mars Attacks! (1996)
Sneakers (1992)
Beavis and Butt-Head Do America (1996)
Last of the Mohicans, The (1992)
Michael (1996)
Private Parts (1997)
Saint, The (1997)
Liar Liar (1997)
Romy and Michele's High School Reunion (1997)
Lost World: Jurassic Park, The (1997)
Con Air (1997)
Batman & Robin (1997)
Hercules (1997)
My Best Friend's Wedding (1997)
G.I. Jane (1997)
Conan the Barbarian (1982)
Conspiracy Theory (1997)
Air Force One (1997)
Kiss the Girls (1997)
The Devil's Advocate (1997)
Stripes (1981)
Starship Troopers (1997)
Anastasia (1997)
Alien: Resurrection (1997)
Scream 2 (1997)
Tomorrow Never Dies (1997)
Wag the Dog (1997)
Dark City (1998)
Sphere (1998)
U.S. Marshals (1998)
Man in the Iron Mask, The (1998)
Wild Things (1998)
Deep Impact (1998)
Six Days Seven Nights (1998)
Mulan (1998)
Dr. Dolittle (1998)
Out of Sight (1998)
Lethal Weapon 4 (1998)
Pi (1998)
Labyrinth (1986)
Halloween (1978)
Poltergeist (1982)
Lethal Weapon 2 (1989)
Lethal Weapon 3 (1992)
Gremlins (1984)
Goonies, The (1985)
Mask of Zorro, The (1998)
Bambi (1942)
Dune (1984)
Flight of the Navigator (1986)
Honey, I Shrunk the Kids (1989)
Negotiator, The (1998)
Jungle Book, The (1967)
Lady and the Tramp (1955)
Mighty Ducks, The (1992)
101 Dalmatians (One Hundred and One Dalmatians) (1961)
Peter Pan (1953)
Rescuers, The (1977)
Rocketeer, The (1991)
Sleeping Beauty (1959)
Splash (1984)
Tron (1982)
Jerk, The (1979)
Addams Family, The (1991)
Ever After: A Cinderella Story (1998)
Adventures in Babysitting (1987)
Weird Science (1985)
Secret of NIMH, The (1982)
Dark Crystal, The (1982)
American Tail, An (1986)
Legend (1985)
NeverEnding Story, The (1984)
Blade (1998)
Willow (1988)
Toys (1992)
Rush Hour (1998)
Ronin (1998)
Thing, The (1982)
Antz (1998)
History of the World: Part I (1981)
Waterboy, The (1998)
Meet Joe Black (1998)
Enemy of the State (1998)
Fletch (1985)
Money Pit, The (1986)
View to a Kill, A (1985)
Police Academy (1984)
Star Trek: Insurrection (1998)
Prince of Egypt, The (1998)
Jewel of the Nile, The (1985)
Cocoon (1985)
Rocky II (1979)
Rocky III (1982)
Clue (1985)
Karate Kid, The (1984)
Karate Kid, Part II, The (1986)
Christmas Vacation (National Lampoon's Christmas Vacation) (1989)
You've Got Mail (1998)
Patch Adams (1998)
Fly, The (1986)
Ruthless People (1986)
Crocodile Dundee (1986)
¡Three Amigos! (1986)
She's All That (1999)
Payback (1999)
Logan's Run (1976)
Planet of the Apes (1968)
Analyze This (1999)
EDtv (1999)
Never Been Kissed (1999)
Entrapment (1999)
Dick Tracy (1990)
Superman II (1980)
Superman III (1983)
Rocky Horror Picture Show, The (1975)
Tarzan (1999)
General's Daughter, The (1999)
Big Daddy (1999)
Arachnophobia (1990)
Wild Wild West (1999)
Ghostbusters II (1989)
Deep Blue Sea (1999)
Mystery Men (1999)
Runaway Bride (1999)
Golden Child, The (1986)
Little Shop of Horrors (1986)
Iron Giant, The (1999)
Thomas Crown Affair, The (1999)
Bowfinger (1999)
Airplane II: The Sequel (1982)
National Lampoon's Vacation (1983)
Pelican Brief, The (1993)
Mickey Blue Eyes (1999)
Excalibur (1981)
Double Jeopardy (1999)
Goldfinger (1964)
From Russia with Love (1963)
Dr. No (1962)
Home Alone 2: Lost in New York (1992)
Time Bandits (1981)
RoboCop (1987)
RoboCop 2 (1990)
Live and Let Die (1973)
Bone Collector, The (1999)
Falling Down (1993)
Spaceballs (1987)
Robin Hood (1973)
Trading Places (1983)
Dead Again (1991)
Sleepy Hollow (1999)
World Is Not Enough, The (1999)
Scrooged (1988)
Fatal Attraction (1987)
Backdraft (1991)
Fisher King, The (1991)
Man on the Moon (1999)
Galaxy Quest (1999)
Sister Act (1992)
Scent of a Woman (1992)
Wayne's World 2 (1993)
League of Their Own, A (1992)
Patriot Games (1992)
Bodyguard, The (1992)
White Men Can't Jump (1992)
Whole Nine Yards, The (2000)
Muppet Movie, The (1979)
Grumpy Old Men (1993)
Jacob's Ladder (1990)
Ladyhawke (1985)
Hook (1991)
Frequency (2000)
Predator (1987)
Keeping the Faith (2000)
Caddyshack (1980)
Spy Who Loved Me, The (1977)
Moonraker (1979)
Man with the Golden Gun, The (1974)
Flatliners (1990)
Running Man, The (1987)
Starman (1984)
Mad Max (1979)
Road Warrior, The (Mad Max 2) (1981)
Big Trouble in Little China (1986)
Titan A.E. (2000)
F/X (1986)
Footloose (1984)
What About Bob? (1991)
Cell, The (2000)
Naked Gun: From the Files of Police Squad!, The (1988)
Naked Gun 2 1/2: The Smell of Fear, The (1991)
Planes, Trains & Automobiles (1987)
Emperor's New Groove, The (2000)
Beverly Hills Cop (1984)
Lost Boys, The (1987)
City Slickers (1991)
Coming to America (1988)
Dirty Rotten Scoundrels (1988)
The Count of Monte Cristo (2002)
Lilo & Stitch (2002)
Professional, The (Le professionnel) (1981)