## Clustering movies

We cluster movies from user ratings using hierarchical and k-means clustering.  Note, the clusters are written to files.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Import the ratings

In [2]:
ratingsData = pd.read_csv('ratings.csv')
ratingsData.head()

   user id  item id  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205

### Import the movie data

In [3]:
movieName = pd.read_csv('movies.csv')
numMovies = len(movieName)
movieName.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

### Create a user by movie matrix that we will cluster.

Note, this will take a moment.

In [4]:
userID = np.unique(ratingsData['user id'])
numUsers = len(userID)
userMovieMatrix = np.zeros((numUsers,numMovies))

for i in range(len(ratingsData)): 
    currentUser   = ratingsData['user id'][i] 
    currentMovie  = ratingsData['item id'][i]
    currentRating = ratingsData['rating'][i]
    
    userIndex = np.where(userID == currentUser)[0]
    movieIndex = np.where(movieName['movieId'] == currentMovie)[0] 
    userMovieMatrix[userIndex,movieIndex] = currentRating

### Let’s now apply hierarchical clustering

In [5]:
from sklearn.cluster import AgglomerativeClustering

numberOfClusters = 10

hierarchicalCluster = AgglomerativeClustering(n_clusters=numberOfClusters, affinity='euclidean', linkage='single')  
hierarchicalCluster.fit_predict(userMovieMatrix.T)

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
import sys
original_stdout = sys.stdout

with open('movieClusterHierarchical.txt', 'w') as f: 
   sys.stdout = f
   # Output the clusters
   for i in range(numberOfClusters):
       index = np.where(hierarchicalCluster.labels_ == i)[0]
       print('\n\nCluster %d' % i)
       for j in range(len(index)):
           print(movieName['title'][index[j]])
   sys.stdout = original_stdout

### Let’s now apply k-means clustering

In [7]:
from sklearn.cluster import KMeans
kmeansCluster = KMeans(n_clusters=numberOfClusters)
kmeansCluster.fit(userMovieMatrix.T)
y_kmeans = kmeansCluster.predict(userMovieMatrix.T)

In [8]:
import sys
original_stdout = sys.stdout

with open('movieClusterKmeans.txt', 'w') as f: 
   sys.stdout = f
   # Output the clusters
   for i in range(numberOfClusters):
       index = np.where(kmeansCluster.labels_ == i)[0]
       print('Cluster %d' % i)
       for j in range(len(index)):
           print(movieName['title'][index[j]])
   sys.stdout = original_stdout

### Let's see what cluster a movie of your choice resides.

In [11]:
yourMovie = 'Karate Kid, The (1984)'

indexOfYourMovieInDataFrame = np.where(movieName['title']==yourMovie)[0]

clusterOfMovie = kmeansCluster.labels_[indexOfYourMovieInDataFrame]
index = np.where(kmeansCluster.labels_ == clusterOfMovie)[0]
print('\nk-means cluster')
print('===============')
for j in range(len(index)):
     print(movieName['title'][index[j]])

# clusterOfMovie = hierarchicalCluster.labels_[indexOfYourMovieInDataFrame]
# index = np.where(hierarchicalCluster.labels_ == clusterOfMovie)[0]
# print('\n\nhierarchical cluster')
# print('===============')
# for j in range(len(index)):
#      print(movieName['title'][index[j]])

k-means cluster
===============
Heat (1995)
American President, The (1995)
Casino (1995)
Ace Ventura: When Nature Calls (1995)
Get Shorty (1995)
Pocahontas (1995)
Mr. Holland's Opus (1995)
From Dusk Till Dawn (1996)
Broken Arrow (1996)
Happy Gilmore (1996)
Birdcage, The (1996)
Desperado (1995)
Mallrats (1995)
Clerks (1994)
Legends of the Fall (1994)
Santa Clause, The (1994)
Crow, The (1994)
Maverick (1994)
Naked Gun 33 1/3: The Final Insult (1994)
Addams Family Values (1993)
Demolition Man (1993)
Hot Shots! Part Deux (1993)
Robin Hood: Men in Tights (1993)
So I Married an Axe Murderer (1993)
Nightmare Before Christmas, The (1993)
Tombstone (1993)
True Romance (1993)
Snow White and the Seven Dwarfs (1937)
Pinocchio (1940)
Primal Fear (1996)
Dragonheart (1996)
James and the Giant Peach (1996)
Truth About Cats & Dogs, The (1996)
Kingpin (1996)
Nutty Professor, The (1996)
Phenomenon (1996)
Ransom (1996)
Wizard of Oz, The (1939)
Cinderella (1950)
Mary Poppins (1964)
Alice in Wonderland (1951)
That Thing You Do! (1996)
William Shakespeare's Romeo + Juliet (1996)
Swingers (1996)
Willy Wonka & the Chocolate Factory (1971)
Fish Called Wanda, A (1988)
Monty Python's Life of Brian (1979)
Dirty Dancing (1987)
Platoon (1986)
Basic Instinct (1992)
Top Gun (1986)
Abyss, The (1989)
Escape from New York (1981)
Wallace & Gromit: The Wrong Trousers (1993)
Brazil (1985)
Army of Darkness (1993)
Blues Brothers, The (1980)
Glory (1989)
Dead Poets Society (1989)
Stand by Me (1986)
Highlander (1986)
Young Frankenstein (1974)
Fantasia (1940)
Heathers (1989)
When Harry Met Sally... (1989)
Alien³ (a.k.a. Alien 3) (1992)
Dracula (Bram Stoker's Dracula) (1992)
Cape Fear (1991)
Carrie (1976)
Star Trek: First Contact (1996)
Die Hard 2 (1990)
Star Trek VI: The Undiscovered Country (1991)
Star Trek II: The Wrath of Khan (1982)
Star Trek III: The Search for Spock (1984)
Star Trek IV: The Voyage Home (1986)
Batman Returns (1992)
Grease (1978)
Jaws (1975)
Mars Attacks! (1996)
Jerry Maguire (1996)
Sneakers (1992)
Beavis and Butt-Head Do America (1996)
Scream (1996)
Last of the Mohicans, The (1992)
Liar Liar (1997)
Grosse Pointe Blank (1997)
Austin Powers: International Man of Mystery (1997)
Lost World: Jurassic Park, The (1997)
Con Air (1997)
My Best Friend's Wedding (1997)
Face/Off (1997)
Contact (1997)
Conspiracy Theory (1997)
Air Force One (1997)
Hunt for Red October, The (1990)
L.A. Confidential (1997)
Game, The (1997)
Chasing Amy (1997)
Full Monty, The (1997)
The Devil's Advocate (1997)
Gattaca (1997)
Stripes (1981)
Starship Troopers (1997)
Jackie Brown (1997)
Wag the Dog (1997)
Dark City (1998)
Wedding Singer, The (1998)
As Good as It Gets (1997)
Deep Impact (1998)
Armageddon (1998)
Pi (1998)
There's Something About Mary (1998)
Rocky (1976)
Labyrinth (1986)
Breakfast Club, The (1985)
Poltergeist (1982)
Exorcist, The (1973)
Lethal Weapon (1987)
Lethal Weapon 2 (1989)
Gremlins (1984)
Goonies, The (1985)
Mask of Zorro, The (1998)
Back to the Future Part II (1989)
Back to the Future Part III (1990)
Honey, I Shrunk the Kids (1989)
Jungle Book, The (1967)
Lady and the Tramp (1955)
Little Mermaid, The (1989)
Peter Pan (1953)
Splash (1984)
Tron (1982)
Jerk, The (1979)
Indiana Jones and the Temple of Doom (1984)
Addams Family, The (1991)
Weird Science (1985)
Dark Crystal, The (1982)
Sixteen Candles (1984)
NeverEnding Story, The (1984)
Beetlejuice (1988)
Willow (1988)
Untouchables, The (1987)
Few Good Men, A (1992)
Rush Hour (1998)
Edward Scissorhands (1990)
Antz (1998)
My Cousin Vinny (1992)
Pleasantville (1998)
Enemy of the State (1998)
Bug's Life, A (1998)
Rushmore (1998)
Shakespeare in Love (1998)
Romancing the Stone (1984)
Cocoon (1985)
Karate Kid, The (1984)
You've Got Mail (1998)
Fly, The (1986)
Crocodile Dundee (1986)
¡Three Amigos! (1986)
Planet of the Apes (1968)
Go (1999)
Election (1999)
Mummy, The (1999)
Star Wars: Episode I - The Phantom Menace (1999)
Superman (1978)
Superman II (1980)
Rocky Horror Picture Show, The (1975)
Notting Hill (1999)
Austin Powers: The Spy Who Shagged Me (1999)
Arachnophobia (1990)
South Park: Bigger, Longer and Uncut (1999)
American Pie (1999)
Blair Witch Project, The (1999)
Ghostbusters II (1989)
Mystery Men (1999)
Little Shop of Horrors (1986)
Iron Giant, The (1999)
Bowfinger (1999)
Airplane! (1980)
Big (1988)
Christmas Story, A (1983)
Three Kings (1999)
Total Recall (1990)
Goldfinger (1964)
Time Bandits (1981)
RoboCop (1987)
Who Framed Roger Rabbit? (1988)
Spaceballs (1987)
Trading Places (1983)
Dogma (1999)
Sleepy Hollow (1999)
Fatal Attraction (1987)
Fisher King, The (1991)
Galaxy Quest (1999)
Talented Mr. Ripley, The (1999)
Fast Times at Ridgemont High (1982)
Wayne's World (1992)
League of Their Own, A (1992)
Patriot Games (1992)
White Men Can't Jump (1992)
Muppet Movie, The (1979)
Erin Brockovich (2000)
Animal House (1978)
Good Morning, Vietnam (1987)
Close Encounters of the Third Kind (1977)
Hook (1991)
Misery (1990)
Predator (1987)
Caddyshack (1980)
Blazing Saddles (1974)
Mad Max (1979)
Chicken Run (2000)
Naked Gun: From the Files of Police Squad!, The (1988)
Best in Show (2000)
Meet the Parents (2000)
Charlie's Angels (2000)
Unbreakable (2000)
Traffic (2000)
Beverly Hills Cop (1984)
Moulin Rouge (2001)
My Big Fat Greek Wedding (2002)
About a Boy (2002)
Chicago (2002)